name: Create a new release

on:
  workflow_dispatch:
    inputs:
      releaseTag:
        description: 'Release Tag'
        required: true
jobs:
  release-ubuntu:
    name: Build for Linux
    runs-on: ubuntu-latest
    env:
      CARGO_TERM_COLOR: always
    steps:
      - uses: actions/checkout@main
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Build-musl
        uses: gmiam/rust-musl-action@0f17df9aea6eadc5eaeccdf733ec78c203103b61
        with:
          args: cargo build --target x86_64-unknown-linux-musl --release
      - name: run clift (linux)
        run: ./target/x86_64-unknown-linux-musl/release/clift --version
      - name: Rename assets (linux)
        run: |
          cp ./target/x86_64-unknown-linux-musl/release/clift ./clift_linux_musl_x86_64
      - name: Update .github/RELEASE_TEMPLATE.md
        run: |
          sed -i "s/GITHUB_SHA/${GITHUB_SHA}/g" .github/RELEASE_TEMPLATE.md
          sed -i "s/DATE/$(date)/g" .github/RELEASE_TEMPLATE.md
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "./clift_linux_musl_x86_64"
          generateReleaseNotes: true
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.event.inputs.releaseTag }}
          bodyFile: .github/RELEASE_TEMPLATE.md
  release-macos:
    name: Build for MacOS
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rs/toolchain@v1
      - name: Run Build
        continue-on-error: false
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release
      - name: run clift (macos)
        run: ./target/release/clift --version
      - name: Rename assets (macos)
        run: |
          cp ./target/release/clift ./clift_macos_x64_latest
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "./clift_macos_x64_latest"
          generateReleaseNotes: true
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.event.inputs.releaseTag }}
          bodyFile: .github/RELEASE_TEMPLATE.md
